/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javabluetoothserver_MediaHandler */

#ifndef _Included_javabluetoothserver_MediaHandler
#define _Included_javabluetoothserver_MediaHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    pressVolUpKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_pressVolUpKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    pressVolDownKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_pressVolDownKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    releaseVolUpKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_releaseVolUpKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    releaseVolDownKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_releaseVolDownKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    pressPlayKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_pressPlayKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    pressFastForwardKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_pressFastForwardKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    pressPreviousKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_pressPreviousKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    releaseFastForwardKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_releaseFastForwardKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    releasePreviousKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_releasePreviousKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    pressSeekForwardKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_pressSeekForwardKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    releaseSeekForwardKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_releaseSeekForwardKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    pressSeekBackwardKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_pressSeekBackwardKey
  (JNIEnv *, jobject);

/*
 * Class:     javabluetoothserver_MediaHandler
 * Method:    releaseSeekBackwardKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javabluetoothserver_MediaHandler_releaseSeekBackwardKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
